"""empty message

Revision ID: 9ac079a88f8c
Revises: 2eccd650f06a
Create Date: 2025-09-03 15:15:00.720982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac079a88f8c'
down_revision = '2eccd650f06a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gstno', sa.String(length=12), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gstno')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
